version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=qmetry_data
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: always

  python_script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_script
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_HOST=influxdb  # Link to InfluxDB service within Docker
    command: ["sh", "-c", "sleep 10 && python ./insert_qmetry_data.py"]  # Wait for InfluxDB to start
    restart: on-failure

volumes:
  influxdb_data:
    driver: local
